name: ng.cash-tech-challenge-mkvlrn
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ng-cash-mkvlrn-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    command: >
      --requirepass root
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ng-cash-mkvlrn-redis-data:/data
  app:
    image: mkvlrn/ng-cash-tech-challenge-mkvlrn:latest
    depends_on:
      - db
      - redis
    build:
      context: .
    restart: always
    ports:
      - 4001:4001
      - 80:4001
volumes:
  ng-cash-mkvlrn-postgres-data:
  ng-cash-mkvlrn-redis-data:
